server:
  error:
    include-exception: false      # Whether the server includes an exception response
    include-message: always       # How do I include response exception messages (never | always | on_param)
    include-stacktrace: on_param  # How do I include response stack traces  (never | always | on_param)
    whitelabel.enabled: true      # Spring boot default error page enabled
  port: 8888

# File Upload Storage Path (macOS local)
app:
  upload:
    dir: /Users/aaron/storage

# File Upload Storage Path (aws remote)
#app:
#  upload:
#    dir: /var/www/leanly/storage

# Maximum allowed multipart file size
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB